#!/bin/sh

addgroup -g ${GID} urlwatch && adduser -h /home/urlwatch -s /bin/sh -G urlwatch -u ${UID} -D urlwatch

chown -R ${UID}:${GID} /home/urlwatch

echo '/15 * * * * GOSU '${GID}':'${GID}' sh -c "urlwatch"' >> /etc/crontabs/root

supervisord -c /etc/supervisord.conf